# docker-compose up
# docker-compose up -d
# docker-compose up --build
# docker-compose up -d --build
# docker-compose build --parallel
# docker-compose ps 
# docker-compose logs -f --tail 10

version: "3.9"
services:

  mysql:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./storage/db/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080